// This file was generated by swagger-codegen.
//
// WARNING: Code you write here will be lost the next time you update the specification

package com.mendix.ux.sassaas.specs.model;


import com.fasterxml.jackson.annotation.JsonProperty;


  public class ResultResponse  {

      private String message = null;

      /**
      *    @ApiModelProperty(required = true, value = "")
      *    
      **/
      @JsonProperty("message")
      public String getMessage() {
          return message;
      }
      public void setMessage(String message) {
          this.message = message;
      }


  @Override
  public String toString()  {
      StringBuilder sb = new StringBuilder();
      sb.append("class ResultResponse {\n");
          
          sb.append("  message: ").append(message).append("\n");
          sb.append("}\n");
          return sb.toString();
      }
  }
