swagger: "2.0"
info:
  version: "0.0.1"
  title: sassaas
host: localhost
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /sass:
    post:
      x-swagger-router-controller: Sass
      description: Returns CSS by compiling an input Sass template
      operationId: compileSass
      consumes:
        - multipart/form-data
      parameters:
        - name: template
          in: formData
          description: sass zip file
          type: file
        - name: variables
          in: query
          description: 'List of variables to apply in JSON format. For instance: [{"color1": "#123"}, {"font": "Sans"}]'
          type: string
        - name: entrypoints
          in: query
          description: 'List of entrypoints to apply in JSON format. For instance: ["index.scss", "custom.scss"]'
          type: string
      responses:
        "200":
          description: Success, a processed template as zip file
          schema:
            type: "file"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
